Setup authentication and Short URL generator logic
afarturc/teeny_url_shortener pull request #2
Opened 2024-03-18 14:42 UTC by afarturc

**Short URL generator:**
1. Hash original URL + user_id using SHA256
2. Encode hashed URL with base62
3. Pick 8 random chars form the encoded URL 

**Notes:**
- The objective of hashing the original url + user id is the uniqueness of the hash. When different users try to use the url shortener it builds different urls.
- After encoding the hash it was still very big, so I decided to follow the strategy of selecting randomly 8 characters from the encoded version, to build the short url.
- The logic was decided based on research, the final approach is very similar as the one described [here](https://www.designgurus.io/blog/url-shortening?gad_source=1&gclid=Cj0KCQjwwMqvBhCtARIsAIXsZpZnIdZ9mFOtoyVRAGOXv2EpcqWwN71a6vyc1gboNfc5CfzwYPxqXhMaAiStEALw_wcB)

2024-03-18 15:45 UTC, afsmarques requested changes

2024-03-18 15:45 UTC, afsmarques commented on app/controllers/links_controller.rb
> +    @link = result.link
do we really need this instance variable? 🤔

2024-03-18 15:45 UTC, afsmarques commented on app/controllers/links_controller.rb
> +        format.json { render json: { link: result.link }, status: :created }
also, if you need the `@link`, you are not using it in here 🤔

2024-03-18 15:45 UTC, afsmarques commented on app/helpers/links_helper.rb
> +module LinksHelper
👀

2024-03-19 09:35 UTC, afarturc commented on app/controllers/links_controller.rb
> +    @link = result.link
I used the instance variable on create.turbo_stream.erb to pass data.
Would it be better to make result an instance variable and use it? Or can I do it in other way?
<img width="1135" alt="Screenshot 2024-03-19 at 09 34 03" src="https://github.com/afarturc/teeny_url_shortener/assets/76447242/dcba2fbf-cb4e-4619-9264-5889024b75fa">

2024-03-19 10:05 UTC, afarturc commented on app/helpers/links_helper.rb
> +module LinksHelper
👀😅

2024-03-19 10:35 UTC, pedroseabra1091 requested changes

2024-03-19 10:35 UTC, pedroseabra1091 commented on app/views/links/create.turbo_stream.erb
> +<%= turbo_stream.prepend "short_links", partial: "links/link_card", locals: { link: @link } %>
💪💪💪

2024-03-19 10:35 UTC, pedroseabra1091 commented on app/views/links/new.html.erb
> +<%= turbo_frame_tag("new_short_link") do %>
Can you clarify why we need a turbo frame here? I'm wondering since the view only holds the frame itself as content.

2024-03-19 10:35 UTC, pedroseabra1091 commented on spec/requests/links_spec.rb
> +        sign_in(user)
We could follow the next example approach and include the shared context 💪

2024-03-19 10:35 UTC, pedroseabra1091 commented on app/services/create_link.rb
> +    short_link = Link.create!(**link_params, short_url: generate_short_url, user_id:)
I'd suggest indexing the `short_url` considering the system will be very read-heavy, especially on that column. The earlier we do it the better as adding an index to already persisted records blocks writes. Rails have tools for that, such as adding the index concurrently. However, we would still be saving a headache by adding sooner rather than later

2024-03-19 10:35 UTC, pedroseabra1091 commented on app/services/base62.rb
> +  end
Can you clarify what will be the use of `decode`?

2024-03-19 10:45 UTC, afarturc commented on app/services/create_link.rb
> +    "teeny.url/#{encode.chars.sample(8).join}"
I only thought about this after starting implementing the redirect in another branch 😅

2024-03-19 11:16 UTC, afarturc commented on app/services/base62.rb
> +  end
The final version of the short URL generator logic does not need the decode.
Another way to do this would be to encode the Link's ID. When retrieving the original_url we would use decode to get the ID. This way we would not need to save the short_url in our link model.
I did not follow this approach because my main priority was always to generate unique hashes with the original_url + user_id.
So ultimately decode is not going to be used and I should have removed it 😅

2024-03-19 11:32 UTC, afarturc commented on app/views/links/new.html.erb
> +<%= turbo_frame_tag("new_short_link") do %>
I want to load the new link view on my index page using the src property.
I had to wrap the view with the turbo_frame_tag so that it was found.

<img width="1037" alt="Screenshot 2024-03-19 at 11 19 02" src="https://github.com/afarturc/teeny_url_shortener/assets/76447242/a33c444d-5cdc-434d-8ba5-34d252d69827">

2024-03-19 14:41 UTC, afsmarques commented on app/controllers/links_controller.rb
> +    @link = result.link
understood! like i said, too rusty... and the fact that we are rendering things for json also contributed to my doubts because i was not understanding why we had to respond to `json` and to the stream, since we are not using that json response on the frontend. (i think 😅 )

2024-03-19 14:41 UTC, afsmarques approved these changes

2024-03-19 15:58 UTC, pedroseabra1091 commented on app/services/base62.rb
> +  end
> Another way to do this would be to encode the Link's ID. When retrieving the original_url we would use decode to get the ID. This way we would not need to save the short_url in our link model.

That's a neat concept! However, it wouldn't be the most optimal solution considering that we would've to decode it on each GET, right? 

Ultimately, it's as you said – if you don't see using it in your final solution it's best to have it removed.

2024-03-19 16:03 UTC, pedroseabra1091 approved these changes

2024-03-19 17:22 UTC, merged